export const TOGGLE_COMPLETION = 'TOGGLE_COMPLETION';
export const GET_TASKS = 'GET_TASKS';
export const GET_ONE_TASK = 'GET_ONE_TASK';
export const GET_TASKS_BY_GROUP = 'GET_TASKS_BY_GROUP';
export const GET_GROUP_NAMES = 'GET_GROUP_NAMES';